Bump bytestring lower bound
```
[1 of 8] Compiling Data.UUID.Named  ( Data/UUID/Named.hs, dist/dist-sandbox-81fa8808/build/Data/UUID/Named.o )

Data/UUID/Named.hs:50:17: Not in scope: `BL.fromStrict'
```

BL.toStrict is introduced in bytestring-0.10